# Generated by Django 5.0.6 on 2024-07-02 14:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_outcome_next_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
