# Generated by Django 5.0.6 on 2024-07-08 18:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_page_content_alter_scenario_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
