# Generated by Django 5.0.6 on 2024-06-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_items', to='home.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
