# Generated by Django 5.0.6 on 2024-06-25 17:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teammember_delete_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
