# Generated by Django 5.0.6 on 2024-06-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_teammember_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='surname',
            new_name='last_name',
        ),
    ]
