# Generated by Django 5.0.6 on 2024-07-10 18:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_missioncontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioncontent',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
