# Generated by Django 5.0.6 on 2024-06-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
        migrations.AddField(
            model_name='drug',
            name='application_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='sponsor_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=10)),
                ('brand_name', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('marketing_status', models.CharField(max_length=50)),
                ('active_ingredients', models.JSONField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='drugs.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(max_length=20)),
                ('submission_number', models.CharField(max_length=10)),
                ('submission_status', models.CharField(max_length=10)),
                ('submission_status_date', models.DateField()),
                ('submission_class_code', models.CharField(max_length=20)),
                ('submission_class_code_description', models.CharField(max_length=255)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='drugs.drug')),
            ],
        ),
    ]
