# Generated by Django 5.0.6 on 2024-06-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_remove_drug_description_remove_drug_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='drug',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
