# Generated by Django 5.0.6 on 2024-06-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0003_remove_submission_drug_delete_product_delete_drug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='side_effects/')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='symptoms/')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('refills', models.IntegerField(default=0)),
                ('dosage', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('dosage_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.route')),
                ('side_effects', models.ManyToManyField(related_name='drugs', to='drugs.sideeffect')),
                ('symptoms', models.ManyToManyField(related_name='drugs', to='drugs.symptom')),
            ],
        ),
    ]
