# Generated by Django 5.0.6 on 2024-06-27 15:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='symptoms',
            new_name='uses',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='dosage_time',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='refills',
        ),
        migrations.AddField(
            model_name='drug',
            name='ingredients',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage',
            field=tinymce.models.HTMLField(),
        ),
    ]
