# Generated by Django 5.0.6 on 2024-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_drug_full_product_details_alter_drug_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drugs/'),
        ),
    ]
