# Generated by Django 5.0.6 on 2024-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_remove_drug_generic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='side_effects/'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symptoms/'),
        ),
    ]
