# Generated by Django 5.0.6 on 2024-06-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_0010_merge_symptom_sideeffect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='conditions',
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(limit_choices_to={'is_side_effect': True}, related_name='drugs_as_side_effect', to='drugs.condition'),
        ),
        migrations.AddField(
            model_name='drug',
            name='uses',
            field=models.ManyToManyField(limit_choices_to={'is_side_effect': False}, related_name='drugs_as_symptom', to='drugs.condition'),
        ),
    ]
