# Generated by Django 5.0.6 on 2024-06-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_remove_drug_conditions_drug_side_effects_drug_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='is_side_effect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='uses',
            field=models.ManyToManyField(related_name='drugs_as_symptom', to='drugs.condition'),
        ),
    ]
