# Generated by Django 5.0.6 on 2024-06-30 01:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_alter_condition_is_side_effect_alter_drug_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
