# Generated by Django 5.0.6 on 2024-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=20, unique=True)),
                ('ind_pac_id', models.CharField(max_length=20)),
                ('ind_enrl_id', models.CharField(max_length=20)),
                ('provider_last_name', models.CharField(max_length=100)),
                ('provider_first_name', models.CharField(max_length=100)),
                ('provider_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('credential', models.CharField(blank=True, max_length=50, null=True)),
                ('med_school', models.CharField(max_length=200)),
                ('grad_year', models.CharField(max_length=4)),
                ('primary_specialty', models.CharField(max_length=200)),
                ('secondary_specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('telehealth', models.CharField(blank=True, max_length=10, null=True)),
                ('facility_name', models.CharField(max_length=200)),
                ('org_pac_id', models.CharField(max_length=20)),
                ('num_org_members', models.CharField(max_length=10)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('telephone_number', models.CharField(max_length=20)),
                ('individual_assignment', models.CharField(max_length=10)),
                ('group_assignment', models.CharField(max_length=10)),
                ('address_id', models.CharField(max_length=20)),
            ],
        ),
    ]
