# Generated by Django 5.0.6 on 2024-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_specialty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='temp_primary_specialty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
