# Generated by Django 5.0.6 on 2024-07-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_temp_primary_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='primary_specialty_v2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors_v2', to='doctors.specialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='primary_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
