# Generated by Django 5.0.6 on 2024-07-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_primary_specialty_v2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='primary_specialty',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='temp_primary_specialty',
        ),
    ]
