# Generated by Django 5.0.6 on 2024-07-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_doctor_primary_specialty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='primary_specialty_v2',
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='doctors.specialty'),
        ),
    ]
